name: Deploy mkdocs blog
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */8 * * *"
jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-publisher
      - name: Build MkDocs site
        run: mkdocs build

      - name: Restore MkDocs cached files
        uses: actions/cache@v3
        with:
          path: .pub_min_cache
          key: mkdocs-publisher-cache-${{ github.run_id }}
          restore-keys: mkdocs-publisher-cache-
      - name: Build mkdocs-publisher documentation
        run: poetry run mkdocs build -c
      - name: Store documentation build and debug logs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs-build-logs
          if-no-files-found: ignore
          retention-days: 1
          path: |
            *_mkdocs_build.log
            *_mkdocs_debug.zip
      - name: Commit static site to repository with GitHub Pages enabled
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOY_PAGES_TOKEN }}
        with:
          user-name: ${{ secrets.USER_NAME }}
          user-email: ${{ secrets.USER_EMAIL }}
          source-directory: docs
          destination-github-username: ${{ secrets.USER_NAME }}
          destination-repository-name: mkdocs-publisher
          target-branch: docs
      - name: Save MkDocs files cache
        uses: actions/cache/save@v3
        with:
          path: .pub_min_cache
          key: mkdocs-publisher-cache-${{ github.run_id }}
